### ISSUE TITLE
Discuss implementing namespaces and abstraction and object oriented design princibles. 

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/RPG-Game#111]
Problem: Current code makes used of global imports among all files. This leads to hidden bugs and name overlap.

Proposed solution: Design and implement a code structure framework. (needs to be keep current).
Example:
Separate code into 3 and only import Objects and Constants between modules.

Suggested sections:

Website --> Anything that is fixed and does not relate to the main game mechanics, mainly would be display elements.
-Pre logon data
--Game marketing
--help
--forums
--password recovery
--account creation --> Access Character.__init__ and stores it with Database.save_game
--login --> Loads world with Database.output/load_game

-Post login --> set up a display for game data, basically a bunch of render modules for game data.
--Main links should all be the same around the border
--render_game --> All game objects should offer a render interface for this object to interact with.

Database --> a basic module to implement "simple, human readable" ways to interact with a database.
-save_game --> basic save character and world state--load_game --> request old character and world state
##efficient_save_load --> Only save changes
 
GameObjects --> The actual game broken down into a bunch of object that interact with each other to make an interesting playable environment. They must include DATA, ACTIONS and DISPLAYS
-LivingObjects --> Note this provides a way to give Monster/NPC gear and other attributes.
--Charaters
---display
--Monsters
---display
--fight
--levelup
--inventory
--display_generic

-Items
--owner
--price
--display

-Locations
--Town
---Shop
----display
---Blacksmith, etc.
---display
--leave
--enter
--display

##Note about display functions.
The website should integrate all display objects as elements of a display grid.
Display objects should use inheritance as much as possible.
![page you see after login_](https://cloud.githubusercontent.com/assets/23045206/20034333/48878584-a377-11e6-9d2c-1da4f6189b8c.jpg)
![page you see after selecting an option_](https://cloud.githubusercontent.com/assets/23045206/20034336/488c11a8-a377-11e6-810b-821e3bc55d37.jpg)
![inventory](https://cloud.githubusercontent.com/assets/23045206/20034335/48889668-a377-11e6-98df-571057a3775a.jpg)
![main page mock-up](https://cloud.githubusercontent.com/assets/23045206/20034334/4888915e-a377-11e6-821d-9c3061aa9ea2.jpg)

And having current mock-ups of what we are trying to build.
Give me your comments :)

**Comment by elthran** [comment]
Hopefully Jimmy can help here, as this is my weakest aspect! I have zero training and don't know any proper implementation or methods. @jimmy-gnahz

**Comment by klondikemarlen** [comment]
I can explain what I mean better too. It isn't super programming complicated. Basically, it is about putting certain concepts in boxes and keeping them there. And isolating certain parts of the project from other parts, so that if you want to change the way the website displays data you don't have to mess with anything other than the website module.

**Comment by jimmy-gnahz** [comment]
Hi, I just saw the message.
Yes good idea. Part of me wants to procrastinate the issue, part of me wants elthran to see the problems after those hidden bugs are revealed and name overlaps actually occur and be like "haha, we should've done it the right way, now lets start over"

**Comment by klondikemarlen** [comment]
Lol. :P well I will work on it slowly and try and entangle stuff as I go. What Elthran has is really fast to prototype with, which is a necessary and hard first step. The other stuff becomes more relevant as the project grows. Which it doesn't without the first step. So the fact that we are beginning to need this kind of thing is good because it means that you guys have got somewhere. :)

**Comment by elthran** [comment]
Marlen
Ok naming conventions:
I read the PEP (they have all of this and more and then some :P). But here goes ...
Class names look like TheNameOfMyObject (singular, not MyObjects plural, eg Hero class not Heroes class. Or User class not Users class. I do this because I am describing a single Hero object and then making lots of them not describing all Hero objects at the same time.
Variable names: my_variable_name is preferred. eg. attack_speed or hero instead of myHero (the myName is a Java convention, the my is implied in Python by the whole "self.varibable convention). If you
Variable names: my_variable_name is preferred. eg. attack_speed or hero instead of myHero (the myName is a Java convention, the my is implied in Python by the whole "self.varibable convention). If you

Marlen
Variable names: my_variable_name is preferred. eg. attack_speed or hero
not myattackspeed or myHero (the myName is a Java convention, the my is implied in Python by the whole "self.varibable convention). Use long names, most editors have autocomplete (Notepad++, Komodo Edit, etc.). Except for local variable: in a for loop you can use min_damage but for a class variable self.minimum_damage is better. Even better 🙂 there is a synonym convention: use self.experience and self.xp = self.experience. They both refer to the same value and one is easier to type when you are feeling lazy or need to put the value in a huge [x for x in list] or (x for x in list) with lots of if statements.

Marlen
Function names should decribe what is happening, sometimes called "verbing" get_name or build_table or update_secondary_attributes. Basically if there is a verb then you know it is a function not a variable ... otherwise they are actually stored the same way and you can only tell them apart by running them (or type(variable) :P).

Marlen
Extra concept: Duck typing. (if it quacks like a duck, walks like a duck, then it might as well be a duck for all I care :P).
Each function should take an input then try: except: to see if it gets the right kind of data.

Marlen
Extra function stuff: from x import * is bad. Use import x then x.function instead. That way when you read the code you can tell where "function" is coming from if it doesn't work properly and you avoid the HUGE problem of naming 2 functions the same name and then overwriting one of them.

Marlen
More function stuff: avoid modifying objects directly unless the method is part of the class. eg. hero = Hero(), hero.update_secondary_attributes() is ok. hero = update_secondary_attributes(hero) [new object created and returned and overwrites the original, original is not modified]. NOT update_secondary_attributes(hero) ... this can cause obscure bugs where you have 1 copy of the same attribute for 2 different heroes. eg. hero1.name = "Marlen" also sets hero2.name to "Marlen" as well.

**Comment by klondikemarlen** [comment]
Note on synonyms:
self.xp = self.experience doesn't necessarily  work.
eg. self.experience = 5
self.xp = self.experience
self.xp = 10
self.expericence != 10 !!! (it still equals 5).

**Comment by klondikemarlen** [comment]
I'm closing this since most of the original problems that are discussed have been fixed.
