### ISSUE TITLE
The proficiency level up buttons seemed to break with your most recent push.

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#200]
Not sure what you did, but it's clearly all your fault :D 

Or it's the stuff that I recently did. Either way, my proficiency command buttons are broken.

**Comment by klondikemarlen** [comment]
Yep. That is my fault. I modified the command code. It is "better" now :P. Should be an easy switch over. I will see if I can patch it today. 
I am trying to design an Event class that would work instead of/or work with the command code. The Event should allow us to build a more generic interface so that if I modify one part the rest of the code doesn't need to be updated.

**Comment by klondikemarlen** [comment]
This has a new branch called "issue200". I have fixed the Command code part ... but now it needs specialized JS code to refresh the page.

**Comment by klondikemarlen** [comment]
Merged branch issue200 into master.
