### ISSUE TITLE
Max_level for profs

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#301]
I don't know what I was thinking earlier. We need a simple max_level function for a prof. It should be like

def is_max_level():
     if prof.level >= prof.attribute.level * 2:
            return True
     return False

Basically, each prof is tied to an attribute.   When you go to the prof level up page, you can't level up a prof more than double the value of the related attribute (though you can boost it with items/abilities just fine, but you cant raise the base value by leveling).  So if you have no strength, then you cant put any points into the damage proficiency (though you could equip a magic sword which DID give you a large amount of damage, your damage level would still be 0 because damage amount and damage level are not always linked).

**Comment by klondikemarlen** [comment]
Ok. Sounds easy ..

**Comment by klondikemarlen** [comment]
Wasn't easy :P fixed in af0a67e6cdc7bd17a226b. Well it was easy just not very intuitive.
At some point I will remove the contain classes and use 'collection_class's instead. Which is I guess what they are for .. finally got the name :P But I want my collection classes to allow you to do:
class['key'] AND class.key ... so that a dictionary pretends to be an object :P
